name: Update DB and display

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL of the zip file"
        required: false
        type: string
  push:
    branches:
      - main

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install unzip and sqlite
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip sqlite3

      - name: Prepare ZIP file
        run: |
          mkdir -p data/unzipped

          if [[ -n "${{ github.event.inputs.zip_url }}" ]]; then
            echo "Downloading ZIP from:"
            echo "${{ github.event.inputs.zip_url }}"

            curl -L "${{ github.event.inputs.zip_url }}" -o data/latest.zip

      - name: Unzip archive
        run: |
          LATEST_ZIP=$(ls -t data/*.zip | head -n 1)

          echo "Latest zip file: $LATEST_ZIP"

          unzip "$LATEST_ZIP" -d data/unzipped

      - name: Run Python script
        run: |
          python parse_activities.py -c data/unzipped/activities.csv -d strava.db

      - name: Distance walked in 2026
        run: |
          sqlite3 -header -column strava.db < queries/distancia_caminhada_em_2026.sql